# Change root password #

# Install prerequisite:
pip3 install passlib


# vim password-change.yml
---
- hosts: all
  become: yes
  tasks:
    - name: Change user password
      user:
        name: admin
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"

###

ansible-playbook password-change.yml --extra-vars newpassword=N3wP@ssword
